### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by anna-parker** [lucanest/Phyloformer#1]
Hi! I recently read your preprint and would love to test your software out on some viral genomes but I seem to not be able to install it properly. When I run your installation instructions I receive this error when I activate the environment: 
```
ERROR: This cross-compiler package contains no program /home/aparker/mambaforge/envs/phylo/bin/x86_64-conda_cos6-linux-gnu-gfortran
INFO: activate-gfortran_linux-64.sh made the following environmental changes:
+HOST=x86_64-conda_cos6-linux-gnu
-HOST=x86_64-conda-linux-gnu
```
and then when I try to run your test script in the environment it tells me that `torch` is not installed, when I install pytorch (`conda install pytorch torchvision -c pytorch`)  I get more errors:
```
python predict.py testdata/alignments
/home/aparker/mambaforge/envs/phylo/lib/python3.9/site-packages/ete3-3.1.2-py3.7.egg/ete3/evol/parser/codemlparser.py:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
/home/aparker/mambaforge/envs/phylo/lib/python3.9/site-packages/ete3-3.1.2-py3.7.egg/ete3/evol/parser/codemlparser.py:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "/home/aparker/Documents/Phyloformer/Phyloformer/predict.py", line 10, in <module>
    from phyloformer.phyloformer import AttentionNet
  File "/home/aparker/Documents/Phyloformer/Phyloformer/phyloformer/__init__.py", line 2, in <module>
    import attentions
ModuleNotFoundError: No module named 'attentions'
```
This leads me to believe that something went very wrong with the installation process. I am running mamba 0.27.0 and conda 22.9.0 on Ubuntu 20.04.4. I additionally tried installing and running the software on an HPC cluster, running CentOS 7.9 and mamba 0.27.0 conda 22.9.0 and this crashes during transaction verification. 

Do you have any suggestions?

**Comment by lucanest** [comment]
Thanks for the feedback, indeed there was also an issue with test.py as at some point I changed the extension with which the trees are saved, with a git pull the problem should be now fixed :)

(and yes ete3 gives that SyntaxWarning on some machines but from my experience it's completely harmless)

**Comment by anna-parker** [comment]
Yes thank you it works well now!
